// Gold_Generator.h: interface for the Gold_Generator class.
//
//////////////////////////////////////////////////////////////////////

#pragma once

//! Structure used by the Gold Generator
struct Mseq {
  unsigned long state; //!< PN register state 
  unsigned long mask;  //!< the mask to get the next state
};



/* Create an ML-sequence generator */
Mseq * mseq_create( unsigned deg, unsigned long poly, unsigned long seed );

/* mseq_free() deallocates the memory space for the m-sequence generator. */
void mseq_free( Mseq * mseq );

/*
 * mseq() gives the next m-sequence bit of the m-sequence generator.
 * The generated bit is unipolar, ie 1 or 0.
 */

int mseq( Mseq * id );

/*
 * mseq() gives the next m-sequence bit of the m-sequence generator.
 * The generated bit is unipolar, ie 1 or 0.
 */
int mseqq( Mseq * id, const int deg );

/*! \file 
\brief Declaration of class Gold_Generator.
*/
/*!  \ingroup Random_Sources
\brief Generator of Gold Sequences.

Gold codes are generated by linearly combining two Maximum-Length (ML) sequences.
Each ML-sequence can be defined by the user in terms of:
- The ML-sequence length \f$N=2^n-1\f$
- The generator polynomial in octal form
- The seed employed for the inizialization of the shift register used to generate the pseudo-random sequence.

If the two polynomials are not specified, default preferred pairs are available for values of 
\f$n\f$ in the range {5,13}.
The number of sequences that are available is \f$2^{n}-1\f$ 
(equal to the number of possible different shift positions between the two ML=sequences). 

  Two methods are available to set the main parametrs of the code (Gold_Generator::SetParameters and 
  Gold_Generator::SetCode).

  For an example of its use see e.g. the test program "test_binary_generator.cpp".

\author Gabriella Bosco
 */


class Gold_Generator  
{
public:
	Gold_Generator();
	virtual ~Gold_Generator();

	//! Set the parameters of the Gold generator.
	void SetParameters(
		const int degree,		//!< Degree of Gold sequences
		int pgen1,				//!< Generator polynomial of first ML sequence
		const int seed1,		//!< Seed of first ML sequence
		int pgen2,				//!< Generator polynomial of second ML sequence
		const int seed2,		//!< Seed of second ML sequence
		const int offsetin=0	//!< Offset of sequence 
		);					

	//! Set the main parameters of the code
	void SetCode(const int degree,	//!< Degree of Gold sequences
				const int ncodein,	//!< Number of the generated code
				const int offset=0,	//!< Sequence offset 
				const int pgen1=0,	//!< Generator polynomial of first ML sequence (if pgen1=0, default preferred pairs are available for values of \f$n\f$ in the range {5,13})
				const int pgen2=0	//!< Generator polynomial of second ML sequence (if pgen2=0, default preferred pairs are available for values of \f$n\f$ in the range {5,13})
				);
	//! Set the offset of the generated sequence
	void SetOffset(
		const int offset	//!< Sequence offset
		){time=offset;};

	//!< Generate the Gold sequence
	void Run(const int tics,	//! Number of putput bits
				int* out		//! Output bit sequence
			);

	//!< Generate the Gold sequence with division circuit
	void RunDiv(const int tics,	//! Number of putput bits
				int* out		//! Output bit sequence
			);

private:
	 Mseq *mseq1;		//!< First ML-sequence
	 Mseq *mseq2;		//!< Second ML-sequence
	int time;			//!< Time index
	int deg;
	static const int table[18]; 	//!< Table containing the default preferred pairs list
};

