// SCCC_Encoder.h: interface for the SCCC_Encoder class.
//
//////////////////////////////////////////////////////////////////////

#pragma once
#include "Trellis.h"
#include "Interleaver.h"
/*! \file
\brief Declaration of class SCCC_Encoder and its interfaces.

 */
/*! \ingroup Codecs
\brief Binary Serial Concatenated Convolutional Code Encoder.
 

The user can specify the trellises of the two encoders and the interleaver. The
trellises must have input and output symbols belonging to the sets \f$U\f$ and \f$C\f$ 
with cardinalities that are powers of
two \f$U=2^k\f$ and \f$C=2^n\f$, so that we can associate to each trellis step a number 
of input bits and output bits. Typical
trellises are then obtained using binary encoder constructed through the interface methods Canonical. 
The interleaver must be a block interleaver.

The SCCC's constituent encoders work in terminated mode and the interleaver is a block interleaver so that the
SCCC as a whole is a block encoder.


A tic of the Run method accepts a block of \f$K\f$ information bits and produces a block 
of \f$N\f$ coded bits.

For an example of its use see e.g. the test program "test_SCCC.cpp".

\author Guido Montorsi
*/
class SCCC_Encoder  
{
public:
	SCCC_Encoder();
	virtual ~SCCC_Encoder();

	//! Set the parameters of the code
	void SetParameters(const Trellis* outer,	//!< Trellis outer encoder.
		const Trellis* inner,			//!< Trellis lower encoder.
		const Interleaver*  interleaver  //!< Interleaver
		);	

	//! Applies puncturing to outer and inner encoders.
	void SetPunct(
		const int po,	//!< Period puncturing outer (0 for no puncturing)
		const int *pato,		//!< Pattern puncturing outer
		const int pi,			//!< Period puncturing inner (0 for no puncturing)
		const int*pati			//!< Pattern puncturing inner
		);
	
	//! Run the encoder
	void Run(const int tics,					//!< Number of encoded blocks
		const int* inp,					//!< Input bits
		int* out,						//!< Output bits
		int* inner=0					//!< Bits at the input of inner encoder (optional)
		);


	int K;			//!< Input bits
	int I;			//!< Interleaver length
	int N;			//!< Output bits
	int* perm;		//!< Permutation
	int* buff;		//!< Internal buffer which stores loop variables

	friend class SCCC_Decoder;

private:

	//! Split output bits of inner encoder in the output frame 
	/*! The bits generated by the inner convolutional encoder are stored into separated
	memory areas. This is useful for specifying different puncturing patterns for different bits.
	Used by the SCCCX* interfaces.
	Warning! this framing is not compatible with the method SetSystematic() */
	bool splitbits;

	int finalstate;	//!< Final state of inner encoder, before termination
	int po;	//!< Period puncturing outer
	int *pato;		//!< Pattern puncturing outer
	int pi;			//!< Period puncturing inner
	int*pati;			//!< Pattern puncturing inner
	Trellis *outer;
	Trellis *inner;
	int nto;		//!< Number of trellis steps outer encoder
	int ko;			//!< Number of input bits  outer encoder
	int no;			//!< Number of output bits outer encoder
	int nti;		//!< Number of trellis steps inner encoder
	int ki;			//!< Number of input bits  inner encoder
	int ni;			//!< Number of output bits inner encoder
	int *to;			//!< input symbol for the termination of outer encoder
	int *ti;			//!< input symbol for the termination of inner encoder
	int ntermo;			//!< Number of steps for the termination of outer encoder
	int ntermi;			//!< Number of steps for the termination of inner encoder
	int Nout[5];		//!< Number of bits for each encoder output


friend
SCCC_Encoder* SCCCX(
					const int K,		
					const int N,		
					const int Rout);


friend
SCCC_Encoder *SCCCXLow(const int K, const int N, const int Rout);

friend 
SCCC_Encoder* SCCCX2(const int K, const int N, const int Rout);



friend SCCC_Encoder* SCCCX3(const int K, const int N, const int Rout);

};

/*! \ingroup Interface
\brief Generate a rate matching SCCC encoder (Rate of outer code: 2/3).

 The code is based on two 4 state rate 1/2 encoders with fix rate 2/3 outer puncturing.
The fixed puncturing pattern is [1110].
Independent puncturing on systematic and parity check bits of inner encoder.
The amount of puncturing of systematic and parity check bits is controlled by
the parameter Rout which range from 200 to 300.

  Any pair (K,N) with K<N, and K/N > 1/3 can be generated.
  The true number of input bits is K-2. The interleaver is read from a file 
  that \b must be in the same directory of executable. 
  The name of the file must be "int_cyc<size>.txt" where <size> is the interleaver 
  size, which is 3/2 of K.
  If K/N< 1/3 the function SCCCXLow is called
*/

SCCC_Encoder* SCCCX(
					const int K,		//!< Input bits (+2)
					const int N,		//!< Output bits
					const int Rout=-1	//!< Parameter to control puncturing of systematic bits, default to automatic computation.
					);

/*! \ingroup Interface
\brief Generate a rate matching SCCC encoder (3/4 outer).

  Code is based on two 4 state rate 1/2 encoder with fix rate 3/4 outer puncturing.
  The fixed puncturing pattern is [111010].
  Independent puncturing on systematic and parity check bits of inner encoder.
  The amount of puncturing of systematic and parity check bits is controlled by
  the parameter Rout which range from 600 to 800.

  Any pair (K,N) with K<N, and K/N > 3/8 can be generated.
  The true number of input bits is K-2. The interleaver is read from a file 
  that \b must be in the same directory of executable. 
  The name of the file must be "int_cyc<size>.txt" where <size> is the interleaver size,
  which is 4/3 of K.
*/

SCCC_Encoder* SCCCX2(const int K, const int N, const int Rout);

/*! \ingroup Interface
\brief Generate a rate matching SCCC encoder (4/6 outer).

  Code is based on two 4 state rate 1/2 encoder with fix rate 2/3 outer puncturing.
  The fixed puncturing pattern is [11111010].
  Independent puncturing on systematic and parity check bits of inner encoder.
  The amount of puncturing of systematic and parity check bits is controlled by
  the parameter Rout which range from 200 to 300.

  Any pair (K,N) with K<N, and K/N > 1/3 can be generated.
  The true number of input bits is K-2. The interleaver is read from a file 
  that \b must be in the same directory of executable. 
  The name of the file must be  "int_cyc<size>.txt" where <size> is the interleaver size,
  which is 3/2 of K.
*/

SCCC_Encoder* SCCCX3(const int K, const int N, const int Rout);