// Walsh_Generator.h: interface for the Walsh_Generator class.
//
//////////////////////////////////////////////////////////////////////

#pragma once

/*! \file 
\brief Declaration of class Walsh_Generator.
*/
/*! \ingroup Random_Sources 
\brief Generator of Hadamard-Walsh Sequences.

The class Walsh_Generator class implements a Walsh code generator. 
Walsh codes are defined using a Hadamard matrix of order \f$2n\f$, with \f$n\f$ integer. 
In particular they are generated by applying Hadamard transform upon 0 repeatedly.
The Walsh code length is equal to \f$N=2^n\f$. A Walsh_Generator with input parameters 
(\f$N\f$, \f$k\f$, \f$n_{\rm offset}\f$) outputs 
the \f$k^{th}\f$ row (with \f$k\in[0,1,N-1]\f$) of the Hadamard matrix \f$H_{2n}\f$ 
shifted by \f$n_{\rm offset}\f$ bits.

  The user specifies:
  - the length of Walsh sequences (power of 2)
  - the code number (corresponding to the Hadamard matrix row number)
  - the offset of the generated sequence

For an example of its use see e.g. the test program "test_binary_generator.cpp".

\author Gabriella Bosco
 */
class Walsh_Generator  
{
public:
	Walsh_Generator();				
	virtual ~Walsh_Generator();		

	//! Set the parameters of the Walsh code
	void SetParameters(
		const int length,		//!< Length of Walsh sequences
		const int ncodein=0,	//!< Number of code generated 
		const int offsetin=0	//!< Offset of sequence
		);				

	//! Select the code among the \f$N\f$ available codes
	void SetCode(const int ncodein	//!< Number of code generated (0...N-1) 
		){ncode=ncodein;};
	//! Set the offset of the generated sequence
	void SetOffset(
		const int offset	//!< Sequence offset
		){time=offset;};

	//! Generate the HW sequence
	void Run(const int tics,	//!< Number of output bits
				int* out		//!< Output bit sequence
				);
private:
	short* codes;					//!< Pointer to the stored codes
	int N;							//!< Length of Walsh sequences
	int ncode;						//!< Number of code generated
	int time;						//!< Internal counter.
};

